### ISSUE TITLE
Each  search leaves a permanent bar at the bottom of the screen

### ISSUE THREAD

**Issue by GreenAsJade** [gangstead/atom-incremental-search#61]
![screenshot 2016-10-25 22 14 48](https://cloud.githubusercontent.com/assets/61894/19684750/8f326690-9b00-11e6-9308-c8f640f035e0.png)

Each of the bars at the bottom of the screen was caused by one use of incremental-search.

I haven't worked out a way to make them go away yet.

**Comment by GreenAsJade** [comment]
I just discovered that this is fixed by an open pull request.   Please merge?

**Comment by gangstead** [comment]
What steps get you to this point?  I just tried doing this multiple times
- <Cmd-I>
- Type some search string
- Hit enter
And each time the panel is being destroyed completely.
I'm on Atom `1.11.2` and atom-incremental-search `5.1.0`

**Comment by GreenAsJade** [comment]
Will undo local hacked in fix and see if I can find out.  It seemed to "just happen all the time"!

**Comment by GreenAsJade** [comment]
OK - wierd.   I can't make it do it anymore.   I have to suspect an interaction with a different package that I may have installed or uninstalled in the mean time :(
