### ISSUE TITLE
Mouse click does not cancel search highlights or search engagement

### ISSUE THREAD

**Issue by craiglyons** [gangstead/atom-incremental-search#62]
### Steps to repro:
* Start an incremental search
* type one or more letters that have at least one match in the document
* mouse click somewhere in the document
* note the search bar is closed, but the highlights remain, and incremental search is still engaged.

This isn't a bug per say, but it seems to me that search engagement should match the ui search bar.
If you're not able to address this soon, I'll take a look; just let me know if you think it should be an option rather than the default behavior. 

Thanks!

**Comment by gangstead** [comment]
That would make an excellent option.  If you make the PR I will happily merge.

**Comment by gangstead** [comment]
Fixed in #63 
Deployed in `incremental-search@v5.2.1`
