### ISSUE TITLE
Deprecated selector in `incremental-search\styles\isearch.less`

### ISSUE THREAD

**Issue by LUDZpro** [gangstead/atom-incremental-search#69]
In `incremental-search\styles\isearch.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor::shadow .isearch-result .region,
atom-text-editor .isearch-result .region` => `atom-text-editor.editor .isearch-result .region,
atom-text-editor .isearch-result .region`

* `atom-text-editor::shadow .isearch-current .region,
atom-text-editor .isearch-current .region` => `atom-text-editor.editor .isearch-current .region,
atom-text-editor .isearch-current .region`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by pbgc** [comment]
It's always good to see other issues... This is duplicating #66 that already has 1year....
I already submitted a PR that fixes this 10months ago... But the repo owner does not merge it.
I use my fork, git clone it and install it locally.
